[versions]
agp = "8.9.1"
jsch = "0.2.25"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.2.1"
gridlayout = "1.0.0"
media3Exoplayer = "1.2.0"
securityCrypto = "1.0.0"
commons-net = "3.8.0"
retrofit = "2.9.0"
okhttp    = "4.11.0"

[libraries]
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
androidx-media3-exoplayer-rtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "media3Exoplayer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
jsch = { module = "com.github.mwiede:jsch", version.ref = "jsch" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version = "1.1.0" }
retrofit      = { module = "com.squareup.retrofit2:retrofit",          version.ref = "retrofit" }
converter-gson= { module = "com.squareup.retrofit2:converter-gson",    version.ref = "retrofit" }
okhttp-logging= { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
commons-net = { group = "commons-net", name = "commons-net", version.ref = "commons-net" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

